name: dart_retrofit
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
dependencies:
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  retrofit: ^4.0.1
